# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentsync" do
  version "0.13.0"

  on_macos do
    on_intel do
      sha256 "d327471233306514924aa7cd6a837f708ede057f9da960beaf76e99e58f01abe"
      url "https://github.com/spxrogers/agentsync/releases/download/v#{version}/agentsync_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/spxrogers/agentsync/"
    end
    on_arm do
      sha256 "bcdd8a593286206cfe7f11bd5e3865886a6f0196f13589b91f79c93a43919b28"
      url "https://github.com/spxrogers/agentsync/releases/download/v#{version}/agentsync_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/spxrogers/agentsync/"
    end
  end

  on_linux do
    on_intel do
      sha256 "e8e227734ad973fcdda93fa3d03959fdc656b5796a06f563ef7ddb34c658248c"
      url "https://github.com/spxrogers/agentsync/releases/download/v#{version}/agentsync_#{version}_linux_amd64.tar.gz",
        verified: "github.com/spxrogers/agentsync/"
    end
    on_arm do
      sha256 "ef73b7892aedc82f61626ed371ff74d77900829e64b1e2c5e3284d1b799d38f0"
      url "https://github.com/spxrogers/agentsync/releases/download/v#{version}/agentsync_#{version}_linux_arm64.tar.gz",
        verified: "github.com/spxrogers/agentsync/"
    end
  end

  name "agentsync"
  desc "Centrally manage AI coding-agent configurations"
  homepage "https://github.com/spxrogers/agentsync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentsync"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentsync"]
    end
  end

  # No zap stanza required

end
