# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentsync" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "e5de78d629d8e8eacf630b2c51f7f541e807719bea5ebcb05e436523b491e0fb"
      url "https://github.com/spxrogers/agentsync/releases/download/v#{version}/agentsync_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/spxrogers/agentsync/"
    end
    on_arm do
      sha256 "f6ea44dd8442ce62b2febfe8b0f8e31e8cd6a06885aa72528f0fc253fcbcf588"
      url "https://github.com/spxrogers/agentsync/releases/download/v#{version}/agentsync_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/spxrogers/agentsync/"
    end
  end

  on_linux do
    on_intel do
      sha256 "8b128968956bf67e9436d2c8385e173fa3b0d9f9b7bc465f154a4df8cca7aa5c"
      url "https://github.com/spxrogers/agentsync/releases/download/v#{version}/agentsync_#{version}_linux_amd64.tar.gz",
        verified: "github.com/spxrogers/agentsync/"
    end
    on_arm do
      sha256 "b5d1eacd13cea0c73ff535c473544eb47011224916ce7d75e39bf161a6127f11"
      url "https://github.com/spxrogers/agentsync/releases/download/v#{version}/agentsync_#{version}_linux_arm64.tar.gz",
        verified: "github.com/spxrogers/agentsync/"
    end
  end

  name "agentsync"
  desc "Centrally manage AI coding-agent configurations"
  homepage "https://github.com/spxrogers/agentsync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentsync"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentsync"]
    end
  end

  # No zap stanza required

end
