# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentsync" do
  version "0.7.5"

  on_macos do
    on_intel do
      sha256 "701db963c0d37b58bce983dc17fe9e64875c12d7c570bc924dc8e23c462959e3"
      url "https://github.com/spxrogers/agentsync/releases/download/v#{version}/agentsync_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/spxrogers/agentsync/"
    end
    on_arm do
      sha256 "177ab56356652fcd0d137b91c204c319f8637c7ce8d7d78d92e894b07f985ee6"
      url "https://github.com/spxrogers/agentsync/releases/download/v#{version}/agentsync_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/spxrogers/agentsync/"
    end
  end

  on_linux do
    on_intel do
      sha256 "258cf5aec191a3cc327b76d6a9c51e67d07578a3347621ba264085b19968f99f"
      url "https://github.com/spxrogers/agentsync/releases/download/v#{version}/agentsync_#{version}_linux_amd64.tar.gz",
        verified: "github.com/spxrogers/agentsync/"
    end
    on_arm do
      sha256 "a7c1386e979319179dc5020331aa526871044879f97c8e940ae11830aac4a70e"
      url "https://github.com/spxrogers/agentsync/releases/download/v#{version}/agentsync_#{version}_linux_arm64.tar.gz",
        verified: "github.com/spxrogers/agentsync/"
    end
  end

  name "agentsync"
  desc "Centrally manage AI coding-agent configurations"
  homepage "https://github.com/spxrogers/agentsync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentsync"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentsync"]
    end
  end

  # No zap stanza required

end
